r"""Generate expectations for the web client's aggregation logic, computed in SQL.

The site filters and aggregates 684 club-seasons in the browser. This writes what the answers should be
for a handful of filter selections, straight from the warehouse, so web/test/aggregates.test.mjs can hold
the TypeScript to the same numbers the dashboard and the scoring layer produce.

The SQL here mirrors the documented aggregation rules: spend summed, points per match as total points over
total matches (not a mean of means), efficiency as the mean of the club's season scores, and medians taken
across the clubs currently displayed.

    .venv\Scripts\python scripts\82_web_expectations.py
"""

import json
import os
from pathlib import Path

import psycopg
from dotenv import load_dotenv

REPO = Path(__file__).resolve().parents[1]
load_dotenv(REPO / ".env")
OUT = REPO / "web" / "test" / "expectations.json"

SCENARIOS = {
    "everything": {"seasons": None, "leagues": None},
    "last three seasons": {"seasons": [2022, 2023, 2024], "leagues": None},
    "premier league only": {"seasons": None, "leagues": ["Premier League"]},
    "one season, two leagues": {"seasons": [2018], "leagues": ["La Liga", "Serie A"]},
}

CLUBS_SQL = """
WITH filtered AS (
    SELECT * FROM presentation.vw_league_overview
    WHERE (%(seasons)s::int[] IS NULL OR season_end_year = ANY(%(seasons)s))
      AND (%(leagues)s::text[] IS NULL OR league = ANY(%(leagues)s))
),
clubs AS (
    SELECT club_key, max(club_name) AS club_name, count(*) AS seasons,
           sum(gross_spend_eur) AS spend, sum(points)::float8 / sum(matches) AS points_per_match,
           avg(efficiency_index) AS efficiency_index, avg(efficiency_score_0_100) AS efficiency_score
    FROM filtered GROUP BY club_key
)
SELECT * FROM clubs ORDER BY efficiency_index DESC, club_name
"""


def main() -> None:
    out = {"note": "generated by scripts/82_web_expectations.py from presentation.vw_league_overview",
           "scenarios": {}}
    with psycopg.connect(os.environ.get("DATABASE_URL", "")) as conn:
        for name, sel in SCENARIOS.items():
            params = {"seasons": sel["seasons"], "leagues": sel["leagues"]}
            cur = conn.execute(CLUBS_SQL, params)
            cols = [d.name for d in cur.description]
            clubs = [dict(zip(cols, r)) for r in cur.fetchall()]
            for c in clubs:
                c["spend"] = float(c["spend"])
                c["efficiency_index"] = float(c["efficiency_index"])
                c["efficiency_score"] = float(c["efficiency_score"])

            plotted = [c for c in clubs if c["spend"] > 0]
            med = lambda xs: (lambda s: (s[len(s) // 2] if len(s) % 2 else (s[len(s) // 2 - 1] + s[len(s) // 2]) / 2))(sorted(xs))

            league_spend = conn.execute("""
                SELECT league, sum(gross_spend_eur) FROM presentation.vw_league_overview
                WHERE (%(seasons)s::int[] IS NULL OR season_end_year = ANY(%(seasons)s))
                  AND (%(leagues)s::text[] IS NULL OR league = ANY(%(leagues)s))
                GROUP BY league ORDER BY sum(gross_spend_eur) DESC""", params).fetchall()

            rows = conn.execute("""
                SELECT count(*) FROM presentation.vw_league_overview
                WHERE (%(seasons)s::int[] IS NULL OR season_end_year = ANY(%(seasons)s))
                  AND (%(leagues)s::text[] IS NULL OR league = ANY(%(leagues)s))""", params).fetchone()[0]

            out["scenarios"][name] = {
                "filters": sel,
                "club_seasons": rows,
                "clubs": len(clubs),
                "total_spend_eur": round(sum(c["spend"] for c in clubs)),
                "median_efficiency_score": med([c["efficiency_score"] for c in clubs]),
                "best_club": clubs[0]["club_name"] if clubs else None,
                "best_index": clubs[0]["efficiency_index"] if clubs else None,
                "top5": [c["club_name"] for c in clubs[:5]],
                "bottom5": [c["club_name"] for c in clubs[-5:]][::-1],
                "median_spend_plotted": med([c["spend"] for c in plotted]) if plotted else 0,
                "median_points_per_match_plotted": med([c["points_per_match"] for c in plotted]) if plotted else 0,
                "spend_by_league": [{"league": l, "spend": round(float(s))} for l, s in league_spend],
                "clubs_without_spend": sum(1 for c in clubs if c["spend"] <= 0),
            }

        # ---- page 2: one club at a time -------------------------------------------------------
        out["clubs"] = {}
        for club_name in ["LOSC Lille", "Chelsea FC", "1. Fußballclub Heidenheim 1846"]:
            key = conn.execute("SELECT club_key FROM dim_club WHERE club_name = %s", (club_name,)).fetchone()[0]
            cash = conn.execute("""
                SELECT sum(fees_paid_eur), sum(fees_received_eur), avg(efficiency_score_0_100),
                       avg(efficiency_index), count(*)
                FROM presentation.vw_cashflow_and_tenure WHERE club_key = %s""", (key,)).fetchone()
            pillars = conn.execute("""
                SELECT avg(recruitment_z) FILTER (WHERE is_recruitment_scored), avg(trading_z),
                       avg(value_growth_z), avg(sporting_z),
                       count(*) FILTER (WHERE NOT is_recruitment_scored)
                FROM presentation.vw_league_overview WHERE club_key = %s""", (key,)).fetchone()
            breakdown = conn.execute("""
                SELECT coalesce(sum(fee_eur) FILTER (WHERE fee_status = 'Fee'), 0),
                       coalesce(sum(fee_eur) FILTER (WHERE fee_status = 'Loan fee'), 0),
                       count(*) FILTER (WHERE fee_status = 'Free'),
                       count(*) FILTER (WHERE fee_status = 'Loan (no fee)'),
                       count(*) FILTER (WHERE fee_status = 'Undisclosed')
                FROM presentation.vw_transfers_detail
                WHERE club_key = %s AND direction IN ('Bought', 'Loan in')""", (key,)).fetchone()
            latest = conn.execute("""
                SELECT max(season_end_year) FROM presentation.vw_current_squad WHERE club_key = %s""", (key,)).fetchone()[0]
            squad = conn.execute("""
                SELECT count(*), coalesce(sum(market_value_eur), 0) FROM presentation.vw_current_squad
                WHERE club_key = %s AND season_end_year = %s""", (key, latest)).fetchone()
            honours = conn.execute("""
                SELECT league_titles, domestic_cups, european_trophies
                FROM presentation.vw_club_trophies_honors WHERE club_key = %s""", (key,)).fetchone()
            managers = conn.execute("""
                SELECT manager_name FROM presentation.vw_cashflow_and_tenure
                WHERE club_key = %s ORDER BY season_end_year""", (key,)).fetchall()
            bands = []
            for (m,) in managers:
                if not bands or bands[-1] != m:
                    bands.append(m)
            top_sales = conn.execute("""
                SELECT player_name, round(fee_eur)::bigint FROM presentation.vw_transfers_detail
                WHERE club_key = %s AND direction = 'Sold' AND fee_eur IS NOT NULL
                ORDER BY fee_eur DESC, player_name LIMIT 3""", (key,)).fetchall()
            out["clubs"][club_name] = {
                "club_key": key,
                "fees_paid_eur": round(float(cash[0])), "fees_received_eur": round(float(cash[1])),
                "net_spend_eur": round(float(cash[0]) - float(cash[1])),
                "efficiency_score": float(cash[2]), "efficiency_index": float(cash[3]), "seasons": cash[4],
                "pillars": {"recruitment": float(pillars[0]) if pillars[0] is not None else None,
                            "trading": float(pillars[1]), "value_growth": float(pillars[2]),
                            "sporting": float(pillars[3]), "seasons_below_spend_floor": pillars[4]},
                "breakdown": {"permanent_eur": round(float(breakdown[0])), "loan_fees_eur": round(float(breakdown[1])),
                              "free_count": breakdown[2], "loan_no_fee_count": breakdown[3],
                              "undisclosed_count": breakdown[4]},
                "latest_season_end_year": latest,
                "latest_squad_players": squad[0], "latest_squad_value_eur": round(float(squad[1])),
                "honours": {"league_titles": honours[0], "domestic_cups": honours[1], "european": honours[2]},
                "manager_bands": bands,
                "top_sales": [[n, int(v)] for n, v in top_sales],
            }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, indent=2), encoding="utf8")
    print(f"wrote {OUT.relative_to(REPO)} with {len(out['scenarios'])} scenarios")
    for name, s in out["scenarios"].items():
        print(f"  {name:24s} {s['clubs']:3d} clubs, {s['club_seasons']:3d} club-seasons, "
              f"spend {s['total_spend_eur']/1e9:.2f}bn, best {s['best_club']}")


if __name__ == "__main__":
    main()
